name: flutter_pos
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: ^3.7.0

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    cupertino_icons: ^1.0.8
    flutter_riverpod: ^2.6.1
    drift: ^2.26.0
    sqlite3_flutter_libs: ^0.5.32
    path_provider: ^2.1.5
    path: ^1.9.1
    flutter_barcode_scanner: ^2.0.0
    intl: ^0.19.0
    pdf: ^3.11.3
    printing: ^5.14.2

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^5.0.0
    drift_dev: ^2.26.0
    build_runner: ^2.4.15

flutter:
    uses-material-design: true
