name: flutter_pos
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: ^3.7.0

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    cupertino_icons: ^1.0.8
    flutter_riverpod: ^2.6.1
    mobile_scanner: ^6.0.7
    intl: ^0.19.0
    pdf: ^3.11.3
    printing: ^5.14.2
    flutter_secure_storage: ^9.2.4
    google_fonts: ^6.2.1

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/fonts/
    fonts:
        - family: DejaVu
          fonts:
              - asset: assets/fonts/DejaVuSans.ttf
              - asset: assets/fonts/DejaVuSans-Bold.ttf
                weight: 700
              - asset: assets/fonts/DejaVuSerif-Italic.ttf
                style: italic
